# Minimum supported Rust version. Should be consistent with CI and mentions
# in crate READMEs.
msrv = "1.79"

# Identifiers that should not trigger the `doc_markdown` lint.
doc-valid-idents = ["OpenMetrics", ".."]
